services:
  server:
    image: node:20-alpine
    container_name: duevora-server-dev
    working_dir: /app/server
    command: node ../scripts/watch-package.js npm run dev -- -L
    volumes:
      # Mount the whole project directory to /app
      - .:/app
      # Mask the local node_modules directory so the container uses its own isolated anonymous volume
      - /app/server/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env


  client:
    image: node:20-alpine
    container_name: duevora-client-dev
    working_dir: /app/client
    command: node ../scripts/watch-package.js npm run dev -- --host
    volumes:
      # Mount the whole project directory to /app
      - .:/app
      # Mask the local node_modules directory so the container uses its own isolated anonymous volume
      - /app/client/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://server:3000
    depends_on:
      - server


