import { jest } from "@jest/globals";
import mongoose from "mongoose";
import { MongoMemoryServer } from "mongodb-memory-server";
import request from "supertest";

// Mock sending mail
jest.unstable_mockModule("../../../shared/utils/sendMail.util.js", () => ({
    __esModule: true,
    default: jest.fn(),
}));

const { default: createApp } = await import("../../../app.js");
const { default: User } = await import("../../../shared/models/user.model.js");
const { default: Organization } = await import("../../../shared/models/organization.model.js");
const { default: Employee } = await import("../../../shared/models/employee.model.js");
const { default: Role } = await import("../../../shared/models/role.model.js");
const { default: Permission } = await import("../../../shared/models/permission.model.js");

let mongoServer;
let app;
let testUser;
let testUserToken;

beforeAll(async () => {
    mongoServer = await MongoMemoryServer.create();
    const uri = mongoServer.getUri();
    await mongoose.connect(uri);
    app = createApp();
});

afterAll(async () => {
    await mongoose.disconnect();
    await mongoServer.stop();
});

beforeEach(async () => {
    const collections = mongoose.connection.collections;
    for (const key in collections) {
        await collections[key].deleteMany({});
    }

    // Create a default verified user for testing
    testUser = await User.create({
        name: "Test User",
        email: "test@example.com",
        password: "password123",
        isVerified: true
    });

    // Mock an access token for this user
    // In our app, the token is generated by createSession, we can log in to get a valid token
    const loginRes = await request(app)
        .post("/api/auth/login")
        .send({ email: "test@example.com", password: "password123" });
    
    testUserToken = loginRes.body.data.accessToken;
});

describe("Organization Onboarding & Retrieval Integration Tests", () => {

    describe("POST /api/organization", () => {
        const onboardPayload = {
            name: "Test Org",
            code: "TORG",
            address: "123 Test St",
            logo: "logo.png",
            firstName: "John",
            lastName: "Doe"
        };

        it("should successfully onboard a new organization, create default roles, and assign employee", async () => {
            // Seed a global permission first
            const perm = await Permission.create({
                name: "View Organization",
                code: "ORGANIZATION.VIEW",
                module: "general"
            });

            const res = await request(app)
                .post("/api/organization")
                .set("Authorization", `Bearer ${testUserToken}`)
                .send(onboardPayload);

            expect(res.status).toBe(201);
            expect(res.body.success).toBe(true);
            expect(res.body.data.organization).toBeDefined();
            expect(res.body.data.organization.code).toBe("TORG");
            expect(res.body.data.employee).toBeDefined();
            expect(res.body.data.employee.employeeCode).toBe("EMP-001");
            expect(res.body.data.accessToken).toBeDefined();

            // Verify that default roles are created
            const roles = await Role.find({ organizationId: res.body.data.organization._id });
            expect(roles.length).toBe(3); // ADMIN, ACCOUNTANT, EMPLOYEE
            expect(roles.map(r => r.code)).toContain("ADMIN");

            // Verify employee role assignment
            const dbEmployee = await Employee.findOne({ userId: testUser._id });
            expect(dbEmployee).toBeDefined();
            expect(dbEmployee.organizationId.toString()).toBe(res.body.data.organization._id.toString());
        });

        it("should fail validation if required fields are missing", async () => {
            const res = await request(app)
                .post("/api/organization")
                .set("Authorization", `Bearer ${testUserToken}`)
                .send({ name: "", code: "A" }); // short code and empty name

            expect(res.status).toBe(400);
            expect(res.body.success).toBe(false);
        });

        it("should return conflict if organization code already exists", async () => {
            await Organization.create({
                name: "Existing Org",
                code: "TORG",
                status: "active"
            });

            const res = await request(app)
                .post("/api/organization")
                .set("Authorization", `Bearer ${testUserToken}`)
                .send(onboardPayload);

            expect(res.status).toBe(409);
            expect(res.body.success).toBe(false);
            expect(res.body.message).toContain("Organization code already exists");
        });
    });

    describe("GET /api/organization", () => {
        it("should retrieve organization details if authorized", async () => {
            // Setup: Onboard first to get an active organization token context
            const perm = await Permission.create({
                name: "View Organization",
                code: "ORGANIZATION.VIEW",
                module: "general"
            });

            const onboardRes = await request(app)
                .post("/api/organization")
                .set("Authorization", `Bearer ${testUserToken}`)
                .send({
                    name: "Acme Corp",
                    code: "ACME",
                    firstName: "Alice",
                    lastName: "Smith"
                });

            const activeToken = onboardRes.body.data.accessToken;

            const res = await request(app)
                .get("/api/organization")
                .set("Authorization", `Bearer ${activeToken}`);

            expect(res.status).toBe(200);
            expect(res.body.success).toBe(true);
            expect(res.body.data.code).toBe("ACME");
            expect(res.body.data.name).toBe("Acme Corp");
        });

        it("should fail with forbidden if user is not associated with an organization", async () => {
            // testUserToken has no organization context
            const res = await request(app)
                .get("/api/organization")
                .set("Authorization", `Bearer ${testUserToken}`);

            expect(res.status).toBe(403);
        });
    });

});
