import { useMemo, useState } from "react";
import { useNavigate } from "react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { HiPlus, HiTrash } from "react-icons/hi2";
import { accountingApi } from "../../api/accountingApi";
import { Button, DataTable, Modal, PageHeader } from "../../../../app/components/common";

const line = () => ({ accountId: "", debit: "", credit: "" });
const input = { boxSizing: "border-box", width: "100%", marginTop: 5, padding: "8px", border: "1px solid #cbd5e1", borderRadius: 6 };

export default function JournalEntryListPage() {
  const qc = useQueryClient();
  const navigate = useNavigate();
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState({ entryNumber: "", date: new Date().toISOString().slice(0, 10), narration: "", lines: [line(), line()] });
  const accountsQuery = useQuery({ queryKey: ["accounts"], queryFn: () => accountingApi.listAccounts(), enabled: open });
  const entriesQuery = useQuery({ queryKey: ["journalEntries"], queryFn: () => accountingApi.listJournalEntries() });
  const totals = useMemo(() => form.lines.reduce((sum, item) => ({ debit: sum.debit + Number(item.debit || 0), credit: sum.credit + Number(item.credit || 0) }), { debit: 0, credit: 0 }), [form.lines]);
  const balanced = totals.debit > 0 && totals.debit === totals.credit && form.lines.every((item) => item.accountId && (Number(item.debit || 0) > 0 || Number(item.credit || 0) > 0));
  const create = useMutation({ mutationFn: accountingApi.createJournalEntry, onSuccess: () => { qc.invalidateQueries({ queryKey: ["journalEntries"] }); setOpen(false); } });
  const updateLine = (index, key, value) => setForm({ ...form, lines: form.lines.map((item, i) => i === index ? { ...item, [key]: value } : item) });
  const submit = (e) => { e.preventDefault(); if (balanced) create.mutate({ ...form, date: new Date(form.date).toISOString(), status: "posted", lines: form.lines.map((item) => ({ accountId: item.accountId, debit: Number(item.debit || 0), credit: Number(item.credit || 0) })) }); };
  const entries = entriesQuery.data?.data || []; const accounts = accountsQuery.data?.data || [];
  return <div style={{ maxWidth: 1300, margin: "0 auto" }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 16 }}><PageHeader title="Journal Entries" subtitle="Create balanced double-entry postings." /><Button variant="primary" onClick={() => setOpen(true)}><HiPlus style={{ marginRight: 6 }} />New journal entry</Button></div><DataTable loading={entriesQuery.isLoading} data={entries} onRowClick={(row) => row._id && navigate(`/dashboard/journal-entries/${row._id}`)} columns={[{ key: "entryNumber", label: "Entry #" }, { key: "date", label: "Date", render: (v) => v ? new Date(v).toLocaleDateString() : "—" }, { key: "narration", label: "Narration" }, { key: "status", label: "Status" }]} />
  <Modal isOpen={open} onClose={() => setOpen(false)} title="Post journal entry"><form onSubmit={submit} style={{ display: "grid", gap: 13 }}><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}><label>Entry number<input required value={form.entryNumber} onChange={(e) => setForm({ ...form, entryNumber: e.target.value })} style={input} /></label><label>Date<input required type="date" value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} style={input} /></label></div><label>Narration<input value={form.narration} onChange={(e) => setForm({ ...form, narration: e.target.value })} style={input} /></label><div><div style={{ display: "grid", gridTemplateColumns: "1fr 100px 100px 32px", gap: 8, fontSize: 12, fontWeight: 700, marginBottom: 6 }}><span>Account</span><span>Debit</span><span>Credit</span><span /></div>{form.lines.map((item, index) => <div key={index} style={{ display: "grid", gridTemplateColumns: "1fr 100px 100px 32px", gap: 8, marginBottom: 8 }}><select required value={item.accountId} onChange={(e) => updateLine(index, "accountId", e.target.value)} style={input}><option value="">Select account</option>{accounts.map((a) => <option key={a._id} value={a._id}>{a.code} — {a.name}</option>)}</select><input type="number" min="0" step="0.01" value={item.debit} onChange={(e) => updateLine(index, "debit", e.target.value)} style={input}/><input type="number" min="0" step="0.01" value={item.credit} onChange={(e) => updateLine(index, "credit", e.target.value)} style={input}/><button type="button" aria-label="Remove line" disabled={form.lines.length === 2} onClick={() => setForm({ ...form, lines: form.lines.filter((_, i) => i !== index) })} style={{ border: 0, background: "none", color: "#dc2626" }}><HiTrash /></button></div>)}</div><Button type="button" variant="secondary" onClick={() => setForm({ ...form, lines: [...form.lines, line()] })}>Add line</Button><div style={{ textAlign: "right", fontWeight: 700, color: balanced ? "#15803d" : "#b45309" }}>Debit: {totals.debit.toFixed(2)} · Credit: {totals.credit.toFixed(2)} {!balanced && "— entries must balance"}</div><div style={{ display: "flex", justifyContent: "flex-end", gap: 10 }}><Button type="button" variant="secondary" onClick={() => setOpen(false)}>Cancel</Button><Button type="submit" variant="primary" disabled={!balanced} loading={create.isPending}>Post entry</Button></div>{create.isError && <small style={{ color: "#b91c1c" }}>{create.error?.response?.data?.message || "Could not post journal entry."}</small>}</form></Modal></div>;
}